<?php
importResource('jframework');
importResource('modernizr');
importResource('webfonts');
importResource('notosans-subset');
importResource('animate.css');
importResource('animate-header');
importResource('modernizr');
importResource('mobile-detect.js');
importResource('ScrollSppedMonitor');
importResource('snap.svg');
importResource('wow.js');
?>
