<?php
importResource('jframework');
importResource('modernizr');
importResource('webfonts');
importResource('notosans-subset-black-and-thin');
importResource('animate.css');
importResource('animate-header');
importResource('modernizr');
importResource('mobile-detect.js');
importResource('ScrollSppedMonitor');
importResource('snap.svg');
importResource('wow.js');
importResource("app-section-triangle",true);
importResource("app-triangle",true);
importResource("app-auto-fontsize",true);
importResource("app-overlay-link",true);
?>
